version: "2"
linters:
  enable:
    - goheader
  settings:
    goheader:
      values:
        const:
          COMPANY: Cofide Limited
        regexp:
          VALID_YEAR: 202[4-9]|20[3-9][0-9]|2[1-9][0-9][0-9]
      template: |-
        Copyright {{ VALID_YEAR }} {{ COMPANY }}.
        SPDX-License-Identifier: Apache-2.0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
